# Site settings
title: Sida Li
email: davidli43@hotmail.com
url: sida.li
description: "Personal website for Sida Li. Graduate in Computer Science and Psychology. Interested in Computer Vision."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Sida Li

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/sida.d.li
  - title: github
    url: https://github.com/davidli43
  - title: bitbucket
    url: https://bitbucket.org/sidali2/

# Build settings
markdown: kramdown
permalink: pretty
