# Site settings
title: Sida Li
email: davidli43 at hotmail.com
url: sida.li
description: "Personal website for Sida Li. Research Programmer at University of Maryland Institute for Advanced Computer Studies"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Sida Li

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/pub/sida-li/58/279/644
  - title: github
    url: https://github.com/davidli43

# Build settings
markdown: kramdown
permalink: pretty
